### PR TITLE
Adjustments for the build-server

### PR DESCRIPTION
**Pull request by MrKepzie**
See commit logs

### CODE REVIEW

**Comment by olear** [comment]
I added py2 to the sdk since several depends wanted it during build, are not used on deployment, but if everything builds without ok :)

**Comment by MrKepzie** [comment]
I built everything without it

**Comment by MrKepzie** [comment]
I committed 2other stuff: 
- I wrongly removed SRC_URL because I thought it was URL to something else, so i renamed it THIRD_PARTY_SRC_URL and I 'm uploading all depends on downloads.natron.fr

**Comment by olear** [comment]
Good, I I was about to upload the sources to downloads myself, will stop the transfer.

**Comment by olear** [comment]
I noticed you removed the creation of the src dir in common.h, build-sdk may/will fail on clean build since the source tarballs can't be downloaded to a non-existing dir.

**Comment by MrKepzie** [comment]
But build-sdk.sh creates it : https://github.com/MrKepzie/natron-linux/blob/master/include/scripts/build-sdk.sh#L29

**Comment by olear** [comment]
Ah, sorry my bad.

unrelated to pull:
I moved ffmpeg over opencv since it (opencv) catches everything it can, regardless of what I say. We should find a way to force the depends there a bit more.

There are some duplicates of some depends in the installer, since I moved as much as possible of the depends to the actual plugin (Libraries), will do a quick review to avoid to many duplicates.

One problem I noticed yesterday was that inpaint/segment don't show up in Natron, the depends are good, and no error message anywhere..

**Pull request merged**
